[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build"
watchPatterns = ["**"]

[service]
rootDirectory = "backend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "5001"
