services:
  - type: web
    name: smart-q-backend
    env: node
    plan: free   # change if you want paid plan
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false   # set this manually in Railway dashboard
